### PR TITLE
Correctly update the properties for all build configurations

### PR DESCRIPTION
**Pull request by bugnano**
This fixes issue #12 

The problem is that getBuildProperty without the last parameter returns only the value of one of the many available build configurations.

Now, what happens if the value returned by getBuildProperty has the expected value, but the other build configurations still have the wrong value? Simple: the plugin (wrongly) assumes that the value does not need to be changed, so it does not update its value, which results in a Cordova project that works in one build configuration, but is totally broken when changing build configuration.

This patch fixes the problem by iterating through each build configuration, and updating the values accordingly.

### CODE REVIEW

**Comment by akofman** [comment]
Thanks ! I'm gonna review that in the week.

**Comment by betko** [comment]
I would like to ask when do you plan to release the fix for this issue? 
Thanks in advance.

**Comment by akofman** [comment]
Hello @betko I have no precise planning cause I do that on my personal time. But probably before the end of the day ;)

**Comment by betko** [comment]
It is sounds good. Thank you. 😸

**Comment by akofman** [comment]
Awesome, thanks @bugnano :+1:

**Pull request merged**
