### PR TITLE
refactor: update tooling, add support for Cordova v9

### LINKED ISSUE #56: Support cordova-cli 9.0.0 - requireCordovaModule deprecation
The use of `context.requireCordovaModule` for non-cordova dependencies has been removed, and suggests you now add the dependency to the plugins `package.json` and `require`'d normally.

https://github.com/apache/cordova-lib/pull/707

### PR DESCRIPTION
**Pull request by timbru31**
First of all **thanks a lot for your project** 👍 

This PR does the follwoing:

- Updates ESLint to the latest versions (and introduces a package-lock.json)
- Fixes npm audit warning by updating xcode dependency
- Kill webpack, babel and Q (no longer needed - Node.js v4 is EOL since nearly 1 year and Node.js v6+ have native Promise support, the webpack generated `add-swift-support.js` was nearly **13.000 lines**!)
- Add semver, glob and xcode dependencies and require them normally (fixes #56)
- Removes Node.js 4 from Travis and adds 8 and 10
- bumped version to v2.0.0 to indicate a breaking change (dropping support of Node.js v4 and older)
- Default Swift version is now 4, since Xcode 10.2 (current) dropped Swift 3 support

### CODE REVIEW

**Comment by timbru31** [comment]
Testing has been done with both Cordova v9 and cordova-ios v4 and v5 with Node.js 8 and 10

**Comment by Tallyb** [comment]
Would be great to see that released!

**Comment by jwuliger** [comment]
Hey guys great work here! When do you expect to merge this branch into master? I could really use it. Thanks!

**Comment by akofman** [comment]
LGTM, Happy Monday ;)

**Comment by lrbalt** [comment]
is it possible to do a release of this plugin? I think it makes it easier to update other plugins that depend on this one

**Comment by akofman** [comment]
@lrbalt, did it and the plugin is published to npm so you also have the possibility to use `"cordova-plugin-add-swift-support": "^2.0.0"` in your `package.json` file and not necessarily a github path.

**Comment by lrbalt** [comment]
thanks @akofman!!!

**Pull request merged**
